# NumPy

In [2]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

## Массивы

In [3]:
a = np.array([1, 4, 5, 8], float) #создание массива
a

array([1., 4., 5., 8.])

In [4]:
type(a)

numpy.ndarray

In [ ]:
#действия с массивами аналогичны действия с обычными списками

In [5]:
a[:2]

array([1., 4.])

In [6]:
a[3]

8.0

In [7]:
a[0] = 5. #присвоение значение элементу массива

In [8]:
a

array([5., 4., 5., 8.])

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]], float) #массивы могут быть многомерными

In [10]:
a[1,:]

array([4., 5., 6.])

In [11]:
a[:,2]

array([3., 6.])

In [12]:
a[-1:, -2:]

array([[5., 6.]])

In [ ]:
# У каждого n-мерного массива есть форма. 
# Например, форма матрицы (двумерного массива) из 3 строк и 5 колонок
# — это (3, 5), 
# форма вектора (вертикального массива) из 10 элементов — это (10, 1).

In [13]:
a.shape

(2, 3)

## Как создать массив стандартных типов

In [ ]:
# eye(N, M=N, k=0) -- двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях.
# Число столбцов M по умолчанию равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа для верхних диагоналей и отрицательные для нижних),
# zeros(shape) -- новый массив указанной формы, заполненный нулями,
# ones(shape) -- новый массив указанной формы, заполненный единицами,
# full(shape, fill_value) -- новый массив указанной формы, заполненный fill_value.

In [14]:
print(np.eye(5, 3, k=-1))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [3]:
#      ДЗ (разминка)
#Создайте и напечатайте (с помощью функции print) 
#массив класса np.ndarray ширины 4 и высоты 3
#с двойками на главной диагонали и единицами на 
#первой диагонали над главной
#Обратите внимание на то, что мы используем Python 3,
#где print() принимает аргументы в скобках.
#Подсказка: простым путём может быть использование
#сложения и умножения на константу.
#просто подставьте нужные значение вместо ..
a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
print(b +2*a)


[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]


## Основные методы ndarray

In [ ]:
# Для работы с многомерными массивами в NumPy реализованы самые
# часто требующиеся операции. Некоторые из них 
# (которые особенно часто будут нужны в нашем курсе)мы сейчас покажем.

In [ ]:
# Форма массива
# a.flatten() — превращает массив в одномерный.
# a.T или a.transpose(*axes) — транспонирование (или смена порядка осей в случае, когда размерность массива больше двух).
# a.reshape(shape) — смена формы массива. Массив "распрямляется" и построчно заполняется в новую форму.

In [5]:
import random
w = np.array(random.sample(range(1000), 12)) 
# одномерный массив из 12 случайных чисел от 1 до 1000
w = w.reshape((2,2,3)) # превратим w в трёхмерную матрицу
print(w)

[[[ 74 572 585]
  [922 197 599]]

 [[323 505 406]
  [241 215 590]]]


In [6]:
mat = w.transpose(0,2,1)
print(mat)

[[[ 74 922]
  [572 197]
  [585 599]]

 [[323 241]
  [505 215]
  [406 590]]]


In [15]:
# ДЗ
# Массив, который нужно было создать в предыдущей задаче
# хранится в переменной mat. 
# Превратите его в вертикальный вектор и напечатайте

w = mat.reshape(-1,1)
print(w)

[[ 74]
 [922]
 [572]
 [197]
 [585]
 [599]
 [323]
 [241]
 [505]
 [215]
 [406]
 [590]]


## Основные методы ndarray 

In [ ]:
Базовые статистики

# a.min(axis=None), a.max(axis=None), a.mean(axis=None), a.std(axis=None)
# — минимум, максимум, среднее арифметическое и стандартное отклонение вдоль указанной оси. 
# По умолчанию ось не указана и статистика считается по всему массиву. 
# a.argmin(axis=None), a.argmax(axis=None)
# — индексы минимального и максимального элемента

In [17]:
v = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]], int)
print(v)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [18]:
print(v.mean(axis=0))  # вдоль столбцов

[1. 2. 3. 4.]


In [19]:
print(v.mean(axis=1))  # вдоль строк

[2.5 2.5 2.5]


In [20]:
print(v.mean(axis=None))  # вдоль всего массива

2.5


In [ ]:
#Чтобы лучше понять, почему говорят «усреднение вдоль оси» — можно нарисовать эту матрицу на бумажке
#и прямыми линиями соединить те элементы, которые сливаются в один при усреднении


## Линейная алгебра

In [ ]:
# Пакет numpy.linalg содержит большую часть стандартных операций и разложений матриц. 
# Некоторые самые популярные функции вынесены в корень пакета NumPy.
# a.dot(b) — матричное произведение двух массивов (размерности должны быть согласованы),
# linalg.matrix_power(M, n) — возведение матрицы M в степень n,
# a.T — транспонирование
# linalg.norm(a, ord=None) — норма матрицы a, по умолчанию норма Фробениуса для матриц и L2-норма для векторов;
# linalg.inv(a) — матрица, обратная к a (если a необратима, выбрасывается LinAlgError; псевдообратная считается через linalg.pinv(a))

In [24]:
w = np.array([[1, 3], [1, 4],[1, 5]])
a = w.dot([[1, 3, 4, 5], [1, 2, 3, 5]])
print(a)

[[ 4  9 13 20]
 [ 5 11 16 25]
 [ 6 13 19 30]]


## Как считать данные из файла:


In [25]:
 sbux = np.loadtxt("sbux.csv", usecols=(0,1,4), skiprows=1, delimiter=",", 
                      dtype={'names': ('date', 'open', 'close'),
                             'formats': ('datetime64[D]', 'f4', 'f4')})

OSError: sbux.csv not found.

In [26]:
print(sbux[0:4])

[('2012-09-12', 50.99, 51.17) ('2012-09-11', 51.  , 50.73)
 ('2012-09-10', 51.18, 50.83) ('2012-09-07', 50.97, 51.17)]


In [ ]:
Здесь использованы не все параметры функции loadtxt (полный их список можно посмотреть в справке).
Разберём имеющиеся, так как они являются наиболее часто встречающимися.
"sbux.csv" — имя файла (или сюда же можно передать объект файла, 
                        такой пример вы увидите в следующей задаче урока), из которого считываются данные.
usecols — список колонок, которые нужно использовать. Если параметр не указан, считываются все колонки.
skiprows — количество рядов в начале файла, которые нужно пропустить. В нашем случае пропущен ряд заголовков. 
По умолчанию (если значение параметра не указано явно) skiprows = 0.
delimiter — разделитель столбцов в одной строке, в csv-файлах это запятая,
по умолчанию разделителем является любой пробел (в том числе — знак табуляции).
dtype — словарь из названий колонок (переменных) и типов хранящихся в них значений. 
NumPy использует свою собственную систему типов, и названия именно этих типов нужно указать. 
По умолчанию функция попытается самостоятельно угадать, какому типу принадлежат подаваемые на вход значения.

In [ ]:
#ДЗ
Задача: считайте данные из файла boston_houses.csv и посчитайте их средние значения.

Файл, из которого нужно считать данные, находится локально,
Первая строчка в файле — названия столбцов, 
остальные строки — числовые данные (то есть каждая строка, кроме первой,
состоит из последовательности вещественных чисел, разделённых запятыми).

Посчитайте и напечатайте вектор из средних значений вдоль столбцов входных данных. 
То есть если файл с входными данными выглядит как

a,b,c,d
1.5,3,4,6
2.5,2,7.5,4
3.5,1,3.5,2

то ответом будет

[ 2.5  2.   5.   4. ]

In [32]:
#вставьте свой код здесь
bost = np.loadtxt("boston_houses.csv", skiprows=1, delimiter=",")
print(bost.mean(axis = 0))

[22.53280632  3.61352356 11.36363636  0.06916996  0.55469506  6.28463439
  3.79504269]
